# Jekyll configuration for GitHub Pages
title: "Policy World Model (PWM)"
description: "From Forecasting to Planning: Policy World Model for Collaborative State-Action Prediction"
baseurl: "/Policy-World-Model"
url: "https://6550Zhao.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README_old.md
  - README.md
  - _temp/
  - ".git*"
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - vendor/
  - node_modules/

# Sass settings
sass:
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"